### ISSUE TITLE
java.lang.NoClassDefFoundError: com/insane/illuminatedbows/client/particles/ColourNitorFX

### ISSUE THREAD

**Issue by XxCoolGamesxX** [MikeLydeamore/IlluminatedBows#11] opened 2015-02-14 17:26 UTC
We use IlluminatedBows-1.7.10-1.7.1b.

```
---- Minecraft Crash Report ----
// You're mean.

Time: 14/02/15 18:18
Description: Initializing game

java.lang.NoClassDefFoundError: com/insane/illuminatedbows/client/particles/ColourNitorFX
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.insane.illuminatedbows.client.particles.ColourNitorFX
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
Caused by: java.lang.NoClassDefFoundError: thaumcraft/client/fx/particles/FXWisp
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more
Caused by: java.lang.ClassNotFoundException: thaumcraft.client.fx.particles.FXWisp
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 90065352 bytes (85 MB) / 265719808 bytes (253 MB) up to 10724048896 bytes (10227 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 45 mods loaded, 45 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed
	ivtoolkit{IvToolkit} [1.0.3] (minecraft.jar) Unloaded->Constructed
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed
	AppleCore{1.1.0} [AppleCore] (APPLECORE-1.1.0.jar) Unloaded->Constructed
	GalacticraftCore{3.0.8} [Galacticraft Core] (GALACTICRAFTCORE-3.0.8.257.jar) Unloaded->Constructed
	GalacticraftMars{3.0.8} [Galacticraft Planets] (GALACTICRAFT-PLANETS-3.0.8.257.jar) Unloaded->Constructed
	MetallurgyCore{4.0.4} [Metallurgy Core] (METALLURGY_CORE-4.0.4.18.jar) Unloaded->Constructed
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (MANTLE-0.3.2.jar) Unloaded->Constructed
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TCONSTRUCT-1.8.2A.jar) Unloaded->Constructed
	Metallurgy{4.0.6} [Metallurgy 4] (METALLURGY-4.0.6.80.jar) Unloaded->Constructed
	B0bGrowsOre{2.1.0} [B0bGary's Growable Ores] (B0BGARY'S GROWABLE ORES-2.1.0.jar) Unloaded->Constructed
	Backpack{2.0.1} [Backpack] (BACKPACK-2.0.1.jar) Unloaded->Constructed
	bountifulbreadsmod{1.0} [Bountiful Bread Mod] (BOUNTIFULBREADSMOD-1.0.jar) Unloaded->Constructed
	compactstorage{v2.0.0a} [CompactStorage] (COMPACTSTORAGE-2.0.0.59.jar) Unloaded->Constructed
	craftguide{1.6.8.1} [CraftGuide] (CRAFTGUIDE-1.6.8.1.jar) Unloaded->Constructed
	customnpcs{1.7.10c} [CustomNpcs] (CUSTOMNPCS-1.7.10C.jar) Unloaded->Constructed
	deconstruction{2.2.5} [The Deconstruction Mod] (DECONSTRUCTION-2.2.5.jar) Unloaded->Constructed
	diversity{ALPHA 1.5} [Diversity] (DIVERSITY-1.5.jar) Unloaded->Constructed
	eplus{3.0.2-d} [Enchanting Plus] (ENCHANTINGPLUS-3.0.2D.jar) Unloaded->Constructed
	ExtraTiC{0.8.4} [ExtraTiC] (EXTRATIC-1.0.3.jar) Unloaded->Constructed
	FastCraft{1.19} [FastCraft] (FASTCRAFT-1.19.jar) Unloaded->Constructed
	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (GRIM3212-CORE-0.2.jar) Unloaded->Constructed
	HardcoreQuesting{The Journey (4.2.2)} [Hardcore Questing Mode] (HQM-THE_JOURNEY-4.2.2.jar) Unloaded->Constructed
	hyperioncraft{1.7.10-0.2.3a} [HyperionCraft] (HYPERIONCRAFT-0.2.3A.jar) Unloaded->Constructed
	iChunUtil{4.1.3} [iChunUtil] (ICHUNUTIL-4.1.3.jar) Unloaded->Constructed
	insane_IlluminatedBows{1.7.1} [Illuminated Bows] (IlluminatedBows-1.7.10-1.7.1b.jar) Unloaded
	imc{1.6} [Improving Minecraft] (IMPROVING_MINECRAFT-1.6.jar) Unloaded
	infinitelava{V0.1 - 1.7.10} [Infinite Lava] (INFINITE_LAVA-0.1.jar) Unloaded
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (INVENTORYTWEAKS-1.59-152.jar) Unloaded
	LomLib{3.0.0} [LomLib] (LOMLIB-3.0.0.jar) Unloaded
	LotsOfFood{1.7.10} [Lots of Food] (LOTS_OF_FOOD-6.jar) Unloaded
	LunatriusCore{1.1.2.21} [LunatriusCore] (LUNATRIUSCORE-1.1.2.21.jar) Unloaded
	MoreArmoursMod{2.0} [MoreArmoursMod] (MORE_ARMOURS_MOD-2.0.jar) Unloaded
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MRCRAYFISH_FURNITURE_MOD-3.4.7.jar) Unloaded
	plo{1.0} [plo] (PLANTS_TO_ORES-1.0.jar) Unloaded
	pokeball{V0.1 - 1.7.10} [Pokeball] (POKEBALL-0.1.jar) Unloaded
	primitivemobs{1.0} [Primitive Mobs] (PRIMITIVEMOBS-1.0C.jar) Unloaded
	rafradek_blocklauncher{1.4.1} [Block Launcher] (RAFRADEK_BLOCKLAUNCHER-1.4.1.jar) Unloaded
	securitycraft{v1.7.2} [SecurityCraft] (SECURITYCRAFT-1.7.2.jar) Unloaded
	transformers{0.4.4} [Transformers Mod] (TRANSFORMERS-0.4.4.jar) Unloaded
	treeores{5.5} [treeores] (TREEORESMOD-5.5.jar) Unloaded
	tnfultimatetoolsforge{1.12.1.0} [Ultimate Tools] (ULTIMATETOOLS-1.12.1.0.jar) Unloaded
	VillagersNose{1.3a} [Villager's Nose] (VILLAGERSNOSE-1.3c.jar) Unloaded
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.52, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```

**Comment by MikeLydeamore** [comment] 2015-02-15 22:58
Was this running on a server?

**Comment by XxCoolGamesxX** [comment] 2015-02-15 22:59
Yes.

**Comment by XxCoolGamesxX** [comment] 2015-02-15 22:59
No.

**Comment by MikeLydeamore** [comment] 2015-02-15 23:54
I think the issue is that you weren't running with thaumcraft, and I was using an unsafe call. Should be fixed now.

**Comment by XxCoolGamesxX** [comment] 2015-02-15 23:54
OK, Thank to help. :D

**Closed** 2015-02-15 23:53 UTC
